import React, { useEffect, useState } from 'react';
import { fetchHistory } from '../services/api';
import { PageHeader, Loader, ErrorMsg, Badge } from '../components/index.jsx';

export default function History() {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);

  useEffect(() => {
    fetchHistory()
      .then(r => setHistory(r.data.data))
      .catch(() => setError('Could not load history.'))
      .finally(() => setLoading(false));
  }, []);

  const formatBadge = f => {
    const map = { view:'badge-green', CSV:'badge-yellow', Excel:'badge-green', PDF:'badge-red' };
    return <span className={map[f] || 'badge-green'}>{f}</span>;
  };

  return (
    <div>
      <PageHeader title="Report History" subtitle="All generated reports in this session"/>
      <div className="card">
        {error   && <ErrorMsg msg={error}/>}
        {loading && <Loader/>}
        {!loading && !error && (
          history.length === 0
            ? <p className="text-center py-12 text-gray-400 text-sm">No history yet. Generate a report first.</p>
            : <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gray-50 border-b border-gray-100">
                    <tr>
                      {['Report','Generated By','Time','Format','Filters'].map(h =>
                        <th key={h} className="th">{h}</th>)}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                    {history.map((h, i) => (
                      <tr key={i} className="hover:bg-gray-50/50">
                        <td className="td font-medium text-gray-900">{h.reportName}</td>
                        <td className="td">{h.generatedBy}</td>
                        <td className="td text-xs text-gray-400">{new Date(h.generatedAt).toLocaleString()}</td>
                        <td className="td">{formatBadge(h.format)}</td>
                        <td className="td text-xs text-gray-400">
                          {Object.entries(h.filters||{}).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(', ') || '—'}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
        )}
      </div>
    </div>
  );
}
